### ISSUE TITLE
the Functions written by assembly and customized have highly possibility to cause problem.

### ISSUE THREAD

**Issue by ParkHanbum** [ParkHanbum/uftrace#5]
# This case associated with _start function. 

### This is the state of the register saved to using as mcount_regs when it reaches main.

CASE : uftrace record -L. tests/t-fibonacci
```
mcount: mcount_entry 7ffebd565a38, 40077e, 7ffebd565a00
mcount: RDI : 2
mcount: RSI : 7ffebd565b18
mcount: RDX : 7ffebd565b30
mcount: RCX : 1a05ff0
mcount: R8 : 0
mcount: R9 : 30
```

CASE : uftrace dynamic -L. tests/t-fibonacci
```
dynamic_entry 7ffdba227760, 4005f6, 7ffdba227728
mcount: mcount_entry 7ffdba227760, 4005f6, 7ffdba227728
mcount: RDI : 3d8a6168
mcount: RSI : 1
mcount: RDX : 7f1e3d68fab0
mcount: RCX : 7ffdba227778
mcount: R8 : 7f1e3d8a66f8
mcount: R9 : 0
mcount: mcount_thread_data
mcount: MOUNT INIT
mcount: new session started: 6a4da7db4a64f21f: t-fibonacci
mcount: found patched address : 4005f0
mcount: Address : 4005f0 14daff0
mcount: PLTHOOK ENTRY :
mcount: dynamic_entry 7ffdba227688, 400816, 7ffdba227650
mcount: mcount_entry 7ffdba227688, 400816, 7ffdba227650
mcount: RDI : 3d46be89
mcount: RSI : 7ffdba227768
mcount: RDX : 146fff0
mcount: RCX : a0
mcount: R8 : 400880
mcount: R9 : 7f1e3d68fab0
mcount: found patched address : 400810
mcount: Address : 400810 14db260
mcount: PLTHOOK ENTRY :
mcount: PLTHOOK ENTRY :
mcount: [mcount_exit] : 7ffdba227670
mcount: mcount_entry 7ffdba227688, 40077e, 7ffdba227650
mcount: RDI : 3d46be89
mcount: RSI : 7ffdba227768
mcount: RDX : 146fff0
mcount: RCX : 0
mcount: R8 : 1
mcount: R9 : 60
```
the RDI register must contain count of arguments at normally. you can see it from "record case". at "record case", RDI have contained number "2". but at "dynamic case", RDI have contained randomize value as abnormally. 

## Diagnosis

the reason is because '_start' function highly customized and do not make frame-point. see _start function prologue. at dynamic tracing, before we discover the problem, there was no reason to exclude the '_start' function. 

```
  4005f0:       31 ed                   xor    %ebp,%ebp
  4005f2:       49 89 d1                mov    %rdx,%r9
  4005f5:       5e                      pop    %rsi
```

but third instruction of _start function have popped the stack without any interaction. 
only we can do that guessing there is some implicit step to use RSI register as argument count. 

problem occured here. 
```
mcount: [0] 4005f0  42 :  _start

mcount: DISASM:
mcount: 0xf1cff0[02]:xor ebp, ebp
mcount: 0xf1cff2[03]:mov r9, rdx
mcount: 0xf1cff5[01]:pop rsi
mcount: 0xf1cff6[06]:jmp qword ptr [rip]

mcount: DISASM:
mcount: 0x4005f0[06]:call qword ptr [rip + 0x200a0a]
```
after some instruction at _start function head have changed to call instruction, it call the __dentry__ pre-called function before calling the mcount_entry. in this situlation, we handle top of the stack value as "child" which mean return address. this is problem, it is not the return address but the "argument count" to popped from stack to RSI. 

for that reason, stack have polluted and cannot execute normally. if program use the argument count like test fibonacci. I think the same thing will happen while uftrace use cases increase.

## Prescription

for now, exclude _start function. 

### Future TASK
**So we have to remember that this case is very important. and we must improve logic to detect same mechanism.**

**Comment by namhyung** [comment]
Do we need to care about `_start` since it's only called by dynamic linker at the very beginning?  It's a special function and won't be called again AFAIK.

**Comment by ParkHanbum** [comment]
@namhyung with LD_PRELOAD will execute _start after dynamic code patching. another words, dynamic code patching works in mcount_init.

**Comment by namhyung** [comment]
Ah, ok.
